name: StageCraftSkyBlock
version: beta-2020.12.12a
api-version: "1.16"
author: Xenry
main: com.xenry.stagecraft.skyblock.SkyBlock
depend: [StageCraftCore]
softdepend: [ProtocolLib,Vault,Essentials,TitleManager,GriefPrevention]
commands:

  # ISLAND COMMANDS
  island:
    description: "Manage your islands"
    aliases: [islands,is]
  islandadmin:
    description: "Manage islands as an admin"
    aliases: [islandsadmin,isa]


