name: StageCraftSkyBlock
version: 2020.10.10.1
api-version: "1.16"
author: Xenry
main: com.xenry.stagecraft.skyblock.SkyBlock
depend: [StageCraftCore]
softdepend: [ProtocolLib,Vault,Essentials,TitleManager,GriefPrevention]
commands:

